apiVersion: v1
kind: Service
metadata:
  name: {{ include "drishti.fullname" . }}-service
  labels:
    {{- include "drishti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "drishti.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8000
    protocol: TCP
  sessionAffinity: {{ .Values.service.sessionAffinity }}
